version: '3.6'

services:
    app:
        image: 'angular-env-test-app'
        build: '.'
        ports:
            - 3005:80
        environment:
            - API_URL=http://${API_DOMAIN}
            - APP_URL=http://${PRIMARY_DOMAIN}